ci: update ci and deployment yml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,115 +1,139 @@
 name: Build and Publish Image to Docker Hub
 on:
-  push:
-    branches:
-    - main
+  release:
+    types: [published]
+  workflow_dispatch:
+
+env:
+  IMAGE_NAME: ghcr.io/${{ github.repository }}
+  IMAGE_TAG: ${{ github.event.release.tag_name  }}
 
 permissions:
   contents: write
+  packages: write
 
 jobs:
-  build-and-push-images:
+  build-and-push:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Build Docker Image
-      run: |
-        docker build -t algn48/node-todo:latest .  
+      - name: Lowercase Repository Name
+        run: |
+          echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
 
-    - name: Login to Docker Hub
-      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "algn48" --password-stdin
+      - name: Determine Image Tag
+        run: |
+          if [ "release" = "release" ]; then
+            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
+          else
+            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
+          fi
 
-    - name: Get Latest Tag from Docker Hub and Increment
-      id: get_tag
-      run: |
-        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/algn48/node-todo/tags/?page_size=1" | jq -r '.results[0].name' | grep -Eo '[0-9]+' || echo 0)
-        NEW_TAG=$((LATEST_TAG + 1))
-        echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
+      - name: Debug Environment Variables
+        run: |
+          echo "IMAGE_NAME: $IMAGE_NAME"
+          echo "IMAGE_TAG: $IMAGE_TAG"
 
-    - name: Push Image to Docker Hub
-      run: |
-        docker tag algn48/node-todo:latest algn48/node-todo:${{ env.new_tag }}
-        docker push algn48/node-todo:${{ env.new_tag }}
+      - name: Set up Docker Buildx 
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push Docker image 
+        uses: docker/build-push-action@v6
+        with: 
+          context: . 
+          push: true 
+          tags: |
+            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+            ${{ env.IMAGE_NAME }}:latest
+          cache-from: type=gha 
+          cache-to: type=gha,mode=max
 
   generate-summary:
     runs-on: ubuntu-latest
-    needs: build-and-push-images
+    needs: build-and-push
     steps:
-    - name: Get Latest Tag from Docker Hub and Increment
-      id: get_tag
-      run: |
-        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/algn48/node-todo/tags/?page_size=1" | jq -r '.results[0].name' | grep -Eo '[0-9]+' || echo 0)
-        NEW_TAG=$((LATEST_TAG ))
-        echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
-    - name: Create Summary for GitHub Actions
-      run: |
-        echo "## ✅ Docker Image Built and Pushed Successfully" >> $GITHUB_STEP_SUMMARY
-        echo "- **Repository:** algn48/node-todo" >> $GITHUB_STEP_SUMMARY
-        echo "- **Latest Tag:** latest" >> $GITHUB_STEP_SUMMARY
-        echo "- **New Incremental Tag:** ${{ env.new_tag }}" >> $GITHUB_STEP_SUMMARY
-        echo "- **Docker Hub URL:** [View Image](https://hub.docker.com/r/algn48/node-todo)" >> $GITHUB_STEP_SUMMARY
+      - name: Get Latest Tag from GitHub Container Registry and Increment
+        id: get_tag
+        run: |
+          LATEST_TAG=$(curl -s "https://ghcr.io/v2/${{ github.repository }}/tags/list" | jq -r '.tags | map(select(test("^[0-9]+$"))) | sort_by(tonumber) | last' || echo 0)
+          NEW_TAG=$((LATEST_TAG + 1))
+          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
+      - name: Create Summary for GitHub Actions
+        run: |
+          echo "##  Docker Image Built and Pushed Successfully" >> $GITHUB_STEP_SUMMARY
+          echo "- **Repository:** ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
+          echo "- **Latest Tag:** latest" >> $GITHUB_STEP_SUMMARY
+          echo "- **New Incremental Tag:** ${{ env.new_tag }}" >> $GITHUB_STEP_SUMMARY
+          echo "- **GitHub Container Registry URL:** [View Image](https://ghcr.io/${{ github.repository }})" >> $GITHUB_STEP_SUMMARY
 
   update-argocd:
     runs-on: ubuntu-latest
     needs: generate-summary
     steps:
-    - name: Clone Target Repository (`argocd-example-apps`)
-      env:
-        GH_TOKEN: ${{ secrets.GH_PAT }}
-      run: |
-        git clone https://gAhmedg:${GH_TOKEN}@github.com/gAhmedg/argocd-example-apps.git target-repo
-        cd target-repo
-        git config --global user.name "github-actions"
-        git config --global user.email "github-actions@github.com"
+      - name: Clone Target Repository (`argocd-example-apps`)
+        env:
+          GH_TOKEN: ${{ secrets.GH_PAT }}
+        run: |
+          git clone https://ahmadnurhidayat:${{ secrets.GITHUB_TOKEN }}@github.com/ahmadnurhidayat/argocd-train.git target-repo
+          cd target-repo
+          git config --global user.name "github-actions"
+          git config --global user.email "github-actions@github.com"
 
-    - name: Get Latest Tag from Docker Hub and Increment
-      id: get_tag
-      run: |
-        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/algn48/node-todo/tags/?page_size=1" | jq -r '.results[0].name' | grep -Eo '[0-9]+' || echo 0)
-        NEW_TAG=$((LATEST_TAG ))
-        echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
+      - name: Get Latest Tag from GitHub Container Registry
+        id: get_tag
+        run: |
+          LATEST_TAG=$(curl -s "https://ghcr.io/v2/${{ github.repository }}/tags/list" | jq -r '.tags | map(select(test("^[0-9]+$"))) | sort_by(tonumber) | last' || echo 0)
+          echo "new_tag=$LATEST_TAG" >> $GITHUB_ENV
 
-    - name: Update Deployment File in `argocd-example-apps`
-      run: |
-        cd target-repo
-        sed -i "s|image: algn48/node-todo:.*|image: algn48/node-todo:${{ env.new_tag }}|g" k8s/deployment.yaml
+      - name: Update Deployment File in `argocd-example-apps`
+        run: |
+          cd target-repo
+          sed -i "s|image: ghcr.io/ahmadnurhidayat/argocd-train:.*|image: ghcr.io/ahmadnurhidayat/argocd-train:${{ env.new_tag }}|g" k8s/deployment.yaml
 
-    - name: Commit and Push Changes to `argocd-example-apps`
-      env:
-        GH_TOKEN: ${{ secrets.GH_PAT }}
-      run: |
-        cd target-repo
-        git add k8s/deployment.yaml
-        git commit -m "Updated deployment with new image tag: ${{ env.new_tag }}"
-        git push https://gAhmedg:${GH_TOKEN}@github.com/gAhmedg/argocd-example-apps.git main
+      - name: Commit and Push Changes to `argocd-example-apps`
+        env:
+          GH_TOKEN: ${{ secrets.GH_PAT }}
+        run: |
+          cd target-repo
+          git add k8s/deployment.yaml
+          git commit -m "Updated deployment with new image tag: ${{ env.new_tag }}"
+          git push https://ahmadnurhidayat:${{ secrets.GITHUB_TOKEN }}@github.com/ahmadnurhidayat/argocd-train.git main
 
-  notify-teams:
-    runs-on: ubuntu-latest
-    needs: [ build-and-push-images, update-argocd ]
-    if: always()
-    steps:
-    - name: Send Teams Notification on Success
-      if: ${{ success() && needs.build-and-push-images.result == 'success' && needs.update-argocd.result == 'success' }}
-      run: |
-        curl -H 'Content-Type: application/json' -d '{
-          "@type": "MessageCard",
-          "@context": "https://schema.org/extensions",
-          "summary": "GitHub Actions Workflow Completed",
-          "themeColor": "00FF00",
-          "title": "✅ Build & Deployment Successful",
-          "text": "**Repository:** algn48/node-todo\n**New Tag:** ${{ env.new_tag }}\n[View Docker Hub](https://hub.docker.com/r/algn48/node-todo)"
-        }' ${{ secrets.TEAMS_WEBHOOK_URL }}
+  # notify-teams:
+  #   runs-on: ubuntu-latest
+  #   needs: [ build-and-push-images, update-argocd ]
+  #   if: always()
+  #   steps:
+  #     - name: Send Teams Notification on Success
+  #       if: ${{ success() && needs.build-and-push-images.result == 'success' && needs.update-argocd.result == 'success' }}
+  #       run: |
+  #         curl -H 'Content-Type: application/json' -d '{
+  #           "@type": "MessageCard",
+  #           "@context": "https://schema.org/extensions",
+  #           "summary": "GitHub Actions Workflow Completed",
+  #           "themeColor": "00FF00",
+  #           "title": "  Build & Deployment Successful",
+  #           "text": "**Repository:** algn48/node-todo\n**New Tag:** ${{ env.new_tag }}\n[View Docker Hub](https://hub.docker.com/r/algn48/node-todo)"
+  #         }' ${{ secrets.TEAMS_WEBHOOK_URL }}
 
-    - name: Send Teams Notification on Failure
-      if: ${{ failure() || needs.build-and-push-images.result != 'success' || needs.update-argocd.result != 'success' }}
-      run: |
-        curl -H 'Content-Type: application/json' -d '{
-          "@type": "MessageCard",
-          "@context": "https://schema.org/extensions",
-          "summary": "GitHub Actions Workflow Failed",
-          "themeColor": "FF0000",
-          "title": "❌ Build & Deployment Failed",
-          "text": "Check GitHub Actions for details."
-        }' ${{ secrets.TEAMS_WEBHOOK_URL }}
+  #     - name: Send Teams Notification on Failure
+  #       if: ${{ failure() || needs.build-and-push-images.result != 'success' || needs.update-argocd.result != 'success' }}
+  #       run: |
+  #         curl -H 'Content-Type: application/json' -d '{
+  #           "@type": "MessageCard",
+  #           "@context": "https://schema.org/extensions",
+  #           "summary": "GitHub Actions Workflow Failed",
+  #           "themeColor": "FF0000",
+  #           "title": "  Build & Deployment Failed",
+  #           "text": "Check GitHub Actions for details."
+  #         }' ${{ secrets.TEAMS_WEBHOOK_URL }}
+
